### ISSUE TITLE
Missing \vendor\autoload.php file

### ISSUE THREAD

**Issue by cornesmit** [techno-express/mailreader#3]
<br />
<b>Warning</b>:  require_once(C:\htdocs\mr\decode\..\vendor\autoload.php): failed to open stream: No such file or directory in <b>C:\htdocs\mr\mailPipe.php</b> on line <b>60</b><br />
<br />
<b>Fatal error</b>:  require_once(): Failed opening required 'C:\htdocs\mr\decode\..\vendor\autoload.php' (include_path='C:\xampp\php\PEAR') in <b>C:\htdocs\mr\mailPipe.php</b> on line <b>60</b><br />

**Comment by TheTechsTech** [comment]
I would need some code snippet you are using.

How are you using the package?
Are you following the tests/examples?

If this is correct then the tests would produce same warning/errors.

**Comment by TheTechsTech** [comment]
not reproducible
